Use git for installing zplug

diff --git a/zsh/zshrc b/zsh/zshrc
--- a/zsh/zshrc
+++ b/zsh/zshrc
@@ -1,20 +1,12 @@
-# Get zplug if it doesn't exist
 ZPLUG_HOME=~/.zplug
 ZPLUG_SHALLOW=false
-if [ ! -f $ZPLUG_HOME/zplug ]; then
-    if hash curl 2>/dev/null; then
-        curl -fLo $ZPLUG_HOME/zplug --create-dirs https://git.io/zplug
-    elif hash wget 2>/dev/null; then
-        if [ ! -d $ZPLUG_HOME ]; then
-            mkdir -p $ZPLUG_HOME
-        fi
-        wget https://git.io/zplug -O $ZPLUG_HOME/zplug
+if [ ! -f $ZPLUG_HOME/init.zsh ]; then
+    if (( $+commands[git] )); then
+        git clone https://github.com/b4b4r07/zplug2 $ZPLUG_HOME
     else
-        echo "Couldn't download zplug" 1>&2
-        return 1
+        echo 'git not found' >&2
+        exit 1
     fi
-
-    source ~/.zplug/init.zsh && zplug update --self
 fi
 
 source $ZPLUG_HOME/init.zsh
